# Generated by Django 4.1.1 on 2022-09-22 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profile_pictures',
            new_name='profile_picture',
        ),
    ]
